"use client";
import {useState,useEffect} from 'react';
import {adminFetch} from './EditorialWorkbench';
import {DAILY_VERSE_THEMES} from '@/lib/dailyVerses';
type Row=Record<string,unknown>;

export function StoryEditor(){
  const [books,setBooks]=useState<Row[]>([]);const [book,setBook]=useState<Row|null>(null);const [message,setMessage]=useState('');
  useEffect(()=>{adminFetch('/api/admin/stories').then(data=>setBooks(data.items)).catch(e=>setMessage(String(e)));},[]);
  const save=async()=>{if(!book)return;try{const fields=['title_hi','summary','summary_hi','story_body','story_body_hi','themes','deities','scripture_references','is_story','published_on'];const updated=await adminFetch('/api/admin/stories',{method:'PUT',body:JSON.stringify({id:book.id,expected_revision:book.revision,...Object.fromEntries(fields.map(k=>[k,book[k]??null]))})});setBook(updated);setBooks(prev=>prev.map(b=>b.id===updated.id?updated:b));setMessage('Story saved. Review and publish its book in Publishing.');}catch(e){setMessage(String(e));}};
  return <div><p>Each feed story is its existing book. Its book ID and page IDs stay stable. Create a book with cover artwork first; curate its narrative here.</p><select aria-label="Choose book" className="form-select" value={String(book?.id??'')} onChange={e=>setBook(books.find(b=>b.id===e.target.value)??null)}><option value="">Choose a book</option>{books.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.title)}</option>)}</select>{!books.length&&<p>No books yet. Use Add New Book.</p>}{book&&<div className="card"><label><input type="checkbox" checked={Boolean(book.is_story)} onChange={e=>setBook({...book,is_story:e.target.checked})}/> Include as a Katha feed story after publication</label>{['title_hi','summary','summary_hi','story_body','story_body_hi'].map(field=><label className="form-group" key={field}><span className="form-label">{{title_hi:'Hindi title',summary:'English summary',summary_hi:'Hindi summary',story_body:'English narrative',story_body_hi:'Hindi narrative'}[field]}</span><textarea className="form-textarea" rows={field.startsWith('story_body')?10:2} value={String(book[field]??'')} onChange={e=>setBook({...book,[field]:e.target.value||null})}/></label>)}{['themes','deities','scripture_references'].map(field=><label className="form-group" key={field}><span className="form-label">{field.replaceAll('_',' ')} (comma-separated)</span><input className="form-input" value={(book[field] as string[]??[]).join(', ')} onChange={e=>setBook({...book,[field]:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label>)}<p>Supported themes: {DAILY_VERSE_THEMES.join(', ')}</p><label className="form-group">Publication date<input className="form-input" type="date" value={String(book.published_on??'').slice(0,10)} onChange={e=>setBook({...book,published_on:e.target.value||null})}/></label><button className="btn btn-primary" onClick={()=>void save()}>Save story</button></div>}{message&&<p role="status">{message}</p>}</div>;
}

const newQuote=()=>({kind:'original_reflection',text:'',locale:'en',attribution:'Bhagwan Bharose editorial team',reference:null,verse_id:null,theme:DAILY_VERSE_THEMES[0],display_date:null,lock_screen_eligible:true} as Row);
export function QuoteEditor(){
  const [items,setItems]=useState<Row[]>([]);const [quote,setQuote]=useState<Row>(newQuote);const [message,setMessage]=useState('');
  const load=()=>adminFetch('/api/admin/quotes').then(data=>setItems(data.items));
  useEffect(()=>{load().catch(e=>setMessage(String(e)));},[]);
  const save=async()=>{try{const data=await adminFetch('/api/admin/quotes',{method:quote.id?'PUT':'POST',body:JSON.stringify({...quote,expected_revision:quote.revision})});setQuote(data);await load();setMessage('Quote saved as editorial content. Review its source in Publishing before making it available.');}catch(e){setMessage(String(e));}};
  return <div className="editorial-grid"><div className="card"><button className="btn btn-secondary" onClick={()=>setQuote(newQuote())}>New quote / reflection</button>{items.map(row=><button className="editorial-row" key={String(row.id)} onClick={()=>setQuote(row)}>{String(row.text)}<small>{String(row.locale)} · {String(row.publication_state)}</small></button>)}</div><div className="card"><label className="form-group">Content kind<select className="form-select" value={String(quote.kind)} onChange={e=>setQuote({...quote,kind:e.target.value})}>{['original_reflection','exact_quote','translated_scripture'].map(k=><option key={k}>{k}</option>)}</select></label>{['text','locale','attribution','reference','verse_id'].map(field=><label className="form-group" key={field}><span className="form-label">{field==='verse_id'?'Linked scripture verse UUID (required for scripture translation)':field}</span><textarea className="form-textarea" rows={field==='text'?5:1} value={String(quote[field]??'')} onChange={e=>setQuote({...quote,[field]:e.target.value||null})}/></label>)}<label className="form-group">Theme<select className="form-select" value={String(quote.theme)} onChange={e=>setQuote({...quote,theme:e.target.value})}>{DAILY_VERSE_THEMES.map(t=><option key={t}>{t}</option>)}</select></label><label className="form-group">Optional scheduled day<input className="form-input" type="date" value={String(quote.display_date??'').slice(0,10)} onChange={e=>setQuote({...quote,display_date:e.target.value||null})}/></label><label><input type="checkbox" checked={Boolean(quote.lock_screen_eligible)} onChange={e=>setQuote({...quote,lock_screen_eligible:e.target.checked})}/> Eligible for lock-screen selection</label><p>The Android user controls whether quotes are shown.</p><button className="btn btn-primary" onClick={()=>void save()}>Save draft / edit</button>{message&&<p role="status">{message}</p>}</div></div>;
}

export function ContributionEditor(){
  const [items,setItems]=useState<Row[]>([]);const [draft,setDraft]=useState<Row>({content_type:'verse',title:'',body:'',locale:'en',source_url:null});const [message,setMessage]=useState('');
  const load=()=>adminFetch('/api/admin/contributions').then(data=>setItems(data.items));
  useEffect(()=>{load().catch(e=>setMessage(String(e)));},[]);
  const save=async(submit=false)=>{try{const saved=await adminFetch('/api/admin/contributions',{method:'POST',body:JSON.stringify(draft)});if(submit)await adminFetch('/api/admin/contributions',{method:'PUT',body:JSON.stringify({id:saved.id})});setDraft({...draft,id:saved.id});await load();setMessage(submit?'Submitted for editorial review.':'Draft saved.');}catch(e){setMessage(String(e));}};
  return <div className="editorial-grid"><div className="card"><h3>Contributions</h3><p>Contributions are drafts for an editor to assess. They cannot publish or delete shared content.</p>{items.map(row=><button className="editorial-row" key={String(row.id)} onClick={()=>setDraft(row)}>{String(row.title)}<small>{String(row.state)}</small></button>)}</div><div className="card"><select aria-label="Contribution type" className="form-select" value={String(draft.content_type)} onChange={e=>setDraft({...draft,content_type:e.target.value})}>{['verse','story','quote','event','media'].map(t=><option key={t}>{t}</option>)}</select>{['title','locale','source_url','body'].map(f=><label className="form-group" key={f}>{f}<textarea className="form-textarea" rows={f==='body'?10:1} value={String(draft[f]??'')} onChange={e=>setDraft({...draft,[f]:e.target.value||null})}/></label>)}<div className="toolbar"><button className="btn btn-primary" onClick={()=>void save()}>Save draft</button><button className="btn btn-secondary" onClick={()=>void save(true)}>Submit for review</button></div>{message&&<p role="status">{message}</p>}</div></div>;
}
